[package]
name = "feedrick"
version = "0.1.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"


[dependencies]
flumedb = "0.1.3"
rayon = "1.2.0"
serde_json = "1.0"
termion = "1"
structopt = "0.3.14"
